version: '3.5'

networks:
  Inception:
    name: Inception
    driver: bridge

volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      device: /home/tarchimb/data/mariadb
      type: volume
      o: bind
  wordpress-vol:
    driver: local
    driver_opts:
      device: /home/tarchimb/data/wordpress
      type: volume
      o: bind

services:

  mariadb:
    image: mariadb
    container_name: maria-db
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    networks:
      - Inception


  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-vol:/var/www/wordpress
    ports:
      - 9000:9000
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - Inception


  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress-vol:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      Inception:
    extra_hosts:
      - "tarchimb.42.fr:127.0.0.1"
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
  