version: '3.5'

  #Volumes:     Use to save memory on the host machine or somewhere else

  #name:        Given name to the volume
  #driver_opts: 
  # device:     Where to store the data on the host machine
  # type:       Type of volume (can be volume, bind-mounts)
  # o:          Options for the volume. Bind to store it on our host machine in the given path
volumes:
  mariadb-vol:
    name: mariadb-volume
    driver_opts:
      device: /home/tarchimb/data/mariadb
      type: volume
      o: bind

  wordpress-vol:
    name: wordpress-volume
    driver_opts:
      device: /home/tarchimb/data/wordpress
      type: volume
      o: bind

#Service plan:

# image:          Name given to the image
# container_name: Name given to the container
# build:
#   context:      Where to find the Dockerfile to build the image
# volumes:        Volumes used for this container (Data saved somewhere outside of the container)
# ports:          Containers_port:Host_port
# restart:        Will restart automatically the container, depends on how it is configure
# env_file:       Pass the .env file to use it in the dockerfile and the container
# networks:       Bind different container together using the same network
# depends-on:     Will wait until the other container finished build

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    networks:
      - Inception

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-vol:/var/www/wordpress
    ports:
      - 9000:9000
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    networks:
      - Inception

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress-vol:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      Inception:
    build: 
      context: ./requirements/nginx
  
  #Networks:  Used to allow container to interact between them

  #name:      Name given to the network
  #driver:    Precise how the container is allowed to use the network, 
  #           bridge is used, so allow to talk with other container on the host machine

networks:
  Inception:
    name: Inception
    driver: bridge

